name: 'Quant Cloud Environment'
description: 'Creates or updates an environment in Quant Cloud'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  api_key:
    description: 'Quant API key'
    required: true
  organization:
    description: 'Quant organisation ID'
    required: true
  app_name:
    description: 'Name of your application'
    required: true
  environment_name:
    description: 'Name for the environment'
    required: true
  base_url:
    description: 'Quant Cloud API URL'
    required: false
    default: 'https://dashboard.quantcdn.io/api/v3'
  from_environment:
    description: 'Name of the environment to clone configuration from (only used when creating a new environment)'
    required: false
  compose_spec:
    description: 'Compose specification for the environment (required for updates, optional for new environments if from_environment is provided)'
    required: false
outputs:
  environment_name:
    description: 'The name of the created or updated environment'
runs:
  using: 'node20'
  main: 'dist/index.js' 